name: Daily Review

on:
  schedule:
    - cron: '0 19 * * *'  # Give it buffer in case start is delayed
      timezone: 'America/New_York'
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.14-trixie-slim

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: uv run -m exampion.main
